sudo: required
language: node_js
node_js:
- '8'
services:
- docker
script:
- docker run --rm -v "$(pwd):/cointoss" holochain/holochain-proto:develop bash -c "cd /cointoss; hcdev test"
- docker run --rm -v "$(pwd):/cointoss" holochain/holochain-proto:develop bash -c "cd /cointoss; hcdev scenario play"
- docker run --rm -v "$(pwd):/cointoss" holochain/holochain-proto:develop bash -c "cd /cointoss; hcdev scenario stress"
